### ISSUE TITLE
Establishing task list to creating milestones for launch

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/shepherd-theme#20]
@chriswallace @garand Please review this list.  I want to make an exhaustive list of items needed to launch Shepherd Pro.  Once the list is complete, please provide estimated times for each task and who is needed and I will create tasks and milestones so we can get this thing launched.  :) 

Below are items I have accumulated from slack conversations and team meetings.

**Free Version:**
- [x] Add on ChurchThemes.net (need to be strategic) 
- [ ] Figure out a way to show the free and paid version side by side 

**Final items to complete to launch paid version of Shepherd Pro:**
- [ ] Chris would like to get the images for it (took this from team agenda - what does this mean?)
- [ ] Look into adding design for a widget for subscribing to an email newsletter #4 
- [ ] Implement color schemes
- [ ] Custom templates
- [ ] #13 
- [ ] #12 
- [ ] #7 
- [ ] Finalize features
- [ ] Finalize layout options
- [ ] Finalize fonts 

**Marketing**
- [ ] Put together features section design and copy (Caleb & Chris)

**Testing**
- [ ] Test all templates (Angela & Brad)

**Documentation**
- [ ] Create support documentation

**Comment by angela-crist** [comment]
@chriswallace Do you want to do anything else with Shepherd or can I can close this?

**Comment by chriswallace** [comment]
Let's close it out for now.
